[workspace]
resolver = "3"
members = [
  "crates/*",
]

[workspace.package]
edition = "2024"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"
publish = false

[workspace.dependencies]
cipher = "0.4"
futures-core = "0.3.31"
futures-io = "0.3"
proptest = "1.6.0"
proptest-state-machine = "0.3.1"
thiserror = "2"
