[workspace]
resolver = "3"
members = [
  "crates/*",
]

[workspace.package]
edition = "2024"
authors = ["Dheatly23 <71598333+Dheatly23@users.noreply.github.com>"]
license = "Apache-2.0"
publish = false

[workspace.dependencies]
cipher = "0.4"
crossbeam-queue = "0.3"
futures-core = "0.3"
futures-io = "0.3"
proptest = "1"
proptest-state-machine = "0.3"
rand = "0.9"
thiserror = "2"
zerocopy = "0.8"
